/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface DeploymentValidatorInterface extends utils.Interface {
  functions: {
    "authorize(address)": FunctionFragment;
    "authorized(address)": FunctionFragment;
    "checkPairValidation(address,address)": FunctionFragment;
    "checkPoolValidation(address)": FunctionFragment;
    "checkWPValidation(address)": FunctionFragment;
    "deauthorize(address)": FunctionFragment;
    "isAuthorized(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "pairs(bytes32)": FunctionFragment;
    "pools(address)": FunctionFragment;
    "setOwner(address)": FunctionFragment;
    "validateAddresses(address,address)": FunctionFragment;
    "validatePoolAddress(address)": FunctionFragment;
    "validateWPAddress(address)": FunctionFragment;
    "wrappedPositions(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "authorize", values: [string]): string;
  encodeFunctionData(functionFragment: "authorized", values: [string]): string;
  encodeFunctionData(
    functionFragment: "checkPairValidation",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "checkPoolValidation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "checkWPValidation",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "deauthorize", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isAuthorized",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pairs", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "pools", values: [string]): string;
  encodeFunctionData(functionFragment: "setOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "validateAddresses",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "validatePoolAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "validateWPAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "wrappedPositions",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "authorize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "authorized", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkPairValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkPoolValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkWPValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deauthorize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pairs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatePoolAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateWPAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrappedPositions",
    data: BytesLike
  ): Result;

  events: {};
}

export interface DeploymentValidator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DeploymentValidatorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    authorize(
      who: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    authorized(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    checkPairValidation(
      wrappedPosition: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    checkPoolValidation(
      pool: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    checkWPValidation(
      wrappedPosition: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    deauthorize(
      who: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isAuthorized(who: string, overrides?: CallOverrides): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pairs(arg0: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    pools(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    setOwner(
      who: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    validateAddresses(
      wrappedPosition: string,
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    validatePoolAddress(
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    validateWPAddress(
      wrappedPosition: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    wrappedPositions(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  authorize(
    who: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  authorized(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  checkPairValidation(
    wrappedPosition: string,
    pool: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  checkPoolValidation(
    pool: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  checkWPValidation(
    wrappedPosition: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  deauthorize(
    who: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isAuthorized(who: string, overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  pairs(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  pools(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  setOwner(
    who: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  validateAddresses(
    wrappedPosition: string,
    pool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  validatePoolAddress(
    pool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  validateWPAddress(
    wrappedPosition: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  wrappedPositions(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    authorize(who: string, overrides?: CallOverrides): Promise<void>;

    authorized(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    checkPairValidation(
      wrappedPosition: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    checkPoolValidation(
      pool: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    checkWPValidation(
      wrappedPosition: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    deauthorize(who: string, overrides?: CallOverrides): Promise<void>;

    isAuthorized(who: string, overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    pairs(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    pools(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    setOwner(who: string, overrides?: CallOverrides): Promise<void>;

    validateAddresses(
      wrappedPosition: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<void>;

    validatePoolAddress(pool: string, overrides?: CallOverrides): Promise<void>;

    validateWPAddress(
      wrappedPosition: string,
      overrides?: CallOverrides
    ): Promise<void>;

    wrappedPositions(arg0: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    authorize(
      who: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    authorized(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    checkPairValidation(
      wrappedPosition: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkPoolValidation(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkWPValidation(
      wrappedPosition: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deauthorize(
      who: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isAuthorized(who: string, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pairs(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    pools(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    setOwner(
      who: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    validateAddresses(
      wrappedPosition: string,
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    validatePoolAddress(
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    validateWPAddress(
      wrappedPosition: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    wrappedPositions(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    authorize(
      who: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    authorized(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkPairValidation(
      wrappedPosition: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkPoolValidation(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkWPValidation(
      wrappedPosition: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deauthorize(
      who: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isAuthorized(
      who: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pairs(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pools(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setOwner(
      who: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    validateAddresses(
      wrappedPosition: string,
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    validatePoolAddress(
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    validateWPAddress(
      wrappedPosition: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    wrappedPositions(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
